### ISSUE TITLE
Feature Request: support for mocking time.Timer

### ISSUE THREAD

**Issue by mattyb** [jonboulle/clockwork#10]
Would be great to see clockwork implement more features of the `time` library.

**Comment by LopatkinEvgeniy** [comment]
+ time.Ticker

**Comment by pierrebeaucamp** [comment]
There are already PRs open for timers and tickers:

Timers: #13 
Tickers: #8

**Comment by jdeal-mediamath** [comment]
Additional PR for Timers: #22

**Comment by sagikazarmark** [comment]
Looks like we have two, mostly abandoned PRs with #22 being the more mature one. If someone wants to pick this up, I'd be happy to review a PR.
