### ISSUE TITLE
FakeClock sleep blocks on negative duration

### ISSUE THREAD

**Issue by redgoattea** [jonboulle/clockwork#19]
According to the golang documentation for [time.Sleep](https://golang.org/pkg/time/#Sleep), when passed a zero or negative duration, the function returns immediately.

FakeClock correctly handles a zero duration, but ends up blocking for negative durations, thus requiring the clock to be advanced by zero to unblock the sleeper (which should never have been blocked to begin with).

**Comment by lyonssp** [comment]
Just opened a PR for a fix #24
