### ISSUE TITLE
make clockwork modules friendly

### ISSUE THREAD

**Issue by mlitvin** [jonboulle/clockwork#20]
Adding go.mod and go.sum is nice, but more important (and simpler) is tagging new version to include "recent" code changes. Without it go take version 0.10 which is quite old.

**Comment by rohansuri** [comment]
Hi @jonboulle,
Is there a plan to create the next tagged release soon?

Thanks

**Comment by grongor** [comment]
Yes, please, tag a new version... :)

**Comment by JohnRoesler** [comment]
Release tag coming soon still?

**Comment by sagikazarmark** [comment]
Done in #23

Will tag a new release soon
