### ISSUE TITLE
Need help with maintenance?

### ISSUE THREAD

**Issue by sagikazarmark** [jonboulle/clockwork#25]
Hi @jonboulle,

First of all, thanks for this package, I think it's a quite popular one!

I noticed there are a couple open issues and PRs and I wonder if you need help with maintenance. Either as a contributor to this repo, or if you don't want to maintain it anymore, as a managed fork somewhere (eg. https://github.com/gofrs).

Let me know what you think!

**Comment by jonboulle** [comment]
You're right, unfortunately I don't really have the capacity any more to provide proper maintenance. 
I would be glad to hand over most of that responsibility if someone is willing to take it on. Are you volunteering yourself? :-)

**Comment by sagikazarmark** [comment]
> Are you volunteering yourself? :-)

I am. :)

**Comment by sagikazarmark** [comment]
Thanks!

I'll do my best!
