### ISSUE TITLE
Tick updates are lost

### ISSUE THREAD

**Issue by empijei** [jonboulle/clockwork#30]
With the current implementation of `FakeClock` updates are lost if more than one is generated at a time.

If, for example, one has a ticker that fires every five minutes and advances the `FakeClock` by one hour they will get *one* tick of five minutes.

This is due to the implementation relying on a [lossy](https://github.com/jonboulle/clockwork/blob/v0.2.2/ticker.go#L65) channel that is [1-buffered](https://github.com/jonboulle/clockwork/blob/v0.2.2/clockwork.go#L150).

My proposal here would be to change this implementation to schedule all needed updates with an unbounded queue.

Simulating time in tests should behave as time should in the actual lifecycle of a program and `FakeClock` currently does not (during real execution the code has time to consume the messages, they don't get sent all at once)

One other possibility would be to allow users to specify a buffer size for tickers when the fake clock is constructed (it's reasonable to assume who is writing the test might know an approximation of the amount of ticks they expect).

Note: In case you are interested in such a change I can send a PR for it.

**Comment by sagikazarmark** [comment]
Thanks for opening an issue @empijei !

Do you have any practical examples in mind where this would be a problem?

Theoretically, you are right, but are there practical use cases for calling `Advance` concurrently?

**Comment by empijei** [comment]
In my case I had a self updating cache that was scheduled to perform some operations every 15' and then check for the time received from the ticker. If an hour was passed since the last update it would also run an update (so more or less once every 4 ticks).

In my tests I would start the server and advance time by an hour, then wait for the cache to emit the "updated" event, which never happened because the last updates would be lost due to this issue.

Would you say this is an intended use for this clockwork?

**Comment by sagikazarmark** [comment]
Oh, I think I misunderstood your issue. So you are not after multiple simultaneous updates of the FakeClock, but receiving all ticks your timer is interested in.

I'd say that's not how clockwork was designed. I mean, what you really want to test is that your code is called every 15 minutes, not that it's called four times in an hour.

But I can see how supporting something like that would be useful.

I'm not actually sure that we can use an unbuffered channel in this case. At least, I'm not sure how that select with the default works in this case. Setting the buffer size sounds like an acceptable solution to me. Probably as a functional option?

**Comment by sagikazarmark** [comment]
Closing as this is how the real clock works as well. If you need to verify that something happened n times, advance and verify one by one.

Feel free to open a new discussion with some examples if it doesn't work for you.
