### ISSUE TITLE
BlockUntil blocks forever if there are too many blockers

### ISSUE THREAD

**Issue by nicks** [jonboulle/clockwork#35]
Consider the following code:

```
func TestFakeClock(t *testing.T) {
	c := clockwork.NewFakeClock()

	go func(){
		c.Sleep(time.Second)
	}()
	go func(){
		c.Sleep(time.Second)
	}()

	c.BlockUntil(1)
}
```

Most of the time this code will pass! But non-deterministically (if the goroutines are scheduled at just the right time), the BlockUntil will block forever.

The problem is that numExpected != numActual (`2 != 1`), so the BlockUntil call will block forever. I think it should be changed so that it blocks until numExpected <= numActual. Would you accept a PR to change this?

I could also imagine other fixes, like BlockUntil panic-ing if there are more sleepers than numExpected, rather than blocking forever.

**Comment by sagikazarmark** [comment]
Hey @nicks !

Thanks for reporting this issue.

If you could provide a patch with appropriate test coverage, that would be awesome!

**Comment by nicks** [comment]
thanks @sagikazarmark ! PR opened - https://github.com/jonboulle/clockwork/pull/36
