### ISSUE TITLE
Fake clock advances past intervening timers 

### ISSUE THREAD

**Issue by muir** [jonboulle/clockwork#46]
I know that the real clock doesn't guarantee that timers will go off exactly on time, but in practice they go off somewhat close to on schedule.

I just created a pull request to add `AfterFunc`.  I noticed when testing it that I can advance the clock well past when a timer is supposed to fire.  The timer fires, but it thinks the time is well past when it _should_ be.

So then, the question is: should the clock pause for real time as it advances past timers?   I think that for `AfterFunc`, it should be willing to wait for `f()` to return or for one real second to pass, whichever comes first.

I don't think any of the other APIs provide any way to know how long to pause.

**Comment by sagikazarmark** [comment]
@muir can you check if the latest (0.4.0) version provides what you are asking for?

**Comment by DPJacques** [comment]
This is almost a year old, and sever months since our attempt to get feedback. If someone can provide reproduction steps, please feel free to reopen.
