### ISSUE TITLE
TestFakeTicker_DeliveryOrder and TestFakeTickerTick are flakey at commit 79f9aa2

### ISSUE THREAD

**Issue by DPJacques** [jonboulle/clockwork#49]
Fast submission just to get this on record:

Test `clockwork/clockwork_test`: `FAILED in 114 out of 1000 in 13.3s` at commit `79f9aa2:`

`TestFakeTicker_DeliveryOrder`:  fails in 113 out of 1000 runs
```
third_party/golang/clockwork/ticker_test.go:119: Expected ticker event didn't arrive!
```

TestFakeTicker_DeliveryOrder:  fails 1 out of 1000 runs
```
third_party/golang/clockwork/ticker_test.go:45: expected tick!
    third_party/golang/clockwork/ticker_test.go:55: wrong tick time, got: 0001-01-01 00:00:00.000000001 +0000 UTC, want: 0001-01-01 00:00:00.000000003 +0000 UTC
```

These issues are not present in v0.3.0, commit `6a247c3 `:

10000 runs: `clockwork:clockwork_test   PASSED in 18.4s`

**Comment by sagikazarmark** [comment]
Thanks for reporting!

Unfortunately, tests started breaking after merging #44

I wanted to give the author opportunity to look into it, because it was a major overhaul and generally it was a good direction.

This is being tracked in #48
