### ISSUE TITLE
Add a reset function to the ticker

### ISSUE THREAD

**Issue by krasi-georgiev** [jonboulle/clockwork#54]
to allow a code like this

```
t := s.clock.NewTicker(s.config.InitialDelay)
var resetOnce sync.Once
defer t.Stop()
for {
	select {
	case <-s.newSlotCh:
		t.Reset(s.config.InitialDelay)
	case <-t.Chan()():
		resetOnce.Do(func() { t.Reset(s.config.PeriodicDelay) })
```

**Comment by DPJacques** [comment]
Ticker already implements reset:

- https://github.com/jonboulle/clockwork/blob/master/ticker.go#L11
- https://github.com/jonboulle/clockwork/blob/master/ticker.go#L33

**Comment by krasi-georgiev** [comment]
ooh, maybe the one that I am importing is an older version.

**Comment by DPJacques** [comment]
The version 3.0.0 doesn't have it yet. I am going to push a few more changes out before asking about bumping the version to 4.0.0.
